cli_exec:
	## ejecutar en conjunto

creador:
	## Compliar y ejecutar creador

productor:
	## Compilar y ejecutar productor

consumidor:
	## Compilar y ejecutar consumidor

finalizador:
	## Compilar y ejecutar finalizador

clean:
	rm -rf *.o *.bin *.elf
